import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, FlaskConical, Leaf, Settings2 } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge, ButtonLink, Callout, Eyebrow, accentSurface } from "@/components/ui";
import { DetailJourneyShell } from "@/components/journey-sidebar";
import { fieldVisual } from "@/components/field-visuals";
import { getCareers, getField, getInstitutions, getPathways, getCourses } from "@/services/catalog";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const field = await getField((await params).slug); return { title: field?.name ?? "Explore an area" }; }
const tabs = ["Overview", "Careers", "Courses & pathways", "Institutions", "Why this?", "Why not?", "What if?"];
const detailVisuals = [FlaskConical, BarChart3, Leaf, Settings2];

export default async function FieldPage({ params }: { params: Promise<{ slug: string }> }) {
  const field = await getField((await params).slug);
  if (!field) notFound();
  const [careers, pathways, courses, institutions] = await Promise.all([getCareers(field.slug), getPathways({ fieldSlug: field.slug }), getCourses({ fieldSlug: field.slug }), getInstitutions({ fieldSlug: field.slug })]);
  const accent = fieldVisual(field.slug).accent;
  const shortCareers = careers.slice(0, 4);
  const subjects = (field.usefulSubjects ?? []).slice(0, 5);
  const image = field.slug === "science-research" ? "/images/field-healthcare.png" : "/images/possibilities-landscape.png";
  return <DetailJourneyShell current={0}>
    <div className="bg-white"><div className="cb-container cb-page mx-auto max-w-[1320px]">
      <header className="flex flex-wrap items-start justify-between gap-6 pb-5"><div><Eyebrow>Explore fields</Eyebrow><h1 className="mt-2 text-[clamp(2.3rem,4.1vw,4.2rem)] font-semibold leading-[1.05] tracking-[-.055em] text-[#071533]">{field.name}</h1><p className="mt-3 text-lg text-ink-500">Ask questions, explore careers, and find what fits you.</p></div><div className="relative hidden h-[98px] w-[390px] overflow-hidden rounded-2xl bg-[#edf5fc] lg:block"><Image src="/images/possibilities-landscape.png" alt="" fill sizes="390px" className="object-cover object-right opacity-65" /><div className="absolute inset-0 bg-gradient-to-r from-[#edf5fc] via-[#edf5fccc] to-transparent" /><p className="relative z-10 max-w-[180px] px-7 py-7 text-sm font-medium text-ink-600">Curious minds<br />build a better tomorrow.</p></div></header>
      <nav aria-label="Field detail sections" className="border-b border-ink-200"><ol className="flex gap-1 overflow-x-auto">{tabs.map((tab, index) => <li key={tab}><a href={index === 0 ? "#overview" : index === 1 ? "#careers" : "#details"} className={`block whitespace-nowrap border-b-[3px] px-5 py-3 text-sm font-semibold ${index === 0 ? "border-[#2877df] text-[#2877df]" : "border-transparent text-ink-500 hover:border-sky-300 hover:text-ink-800"}`}>{tab}</a></li>)}</ol></nav>
      <main className="mt-5 space-y-7">
        <section id="overview" className="relative grid min-h-[350px] overflow-hidden rounded-2xl bg-[#f3f7fc] lg:grid-cols-[52%_48%]" aria-labelledby="overview-title"><div className="relative z-10 flex flex-col justify-center px-8 py-9 sm:px-10"><Eyebrow>Explore this field</Eyebrow><h2 id="overview-title" className="mt-3 max-w-[20ch] text-[clamp(1.8rem,3vw,2.6rem)] font-semibold leading-[1.08] text-[#071533]">What is {field.name}?</h2><p className="mt-4 max-w-[52ch] text-base leading-relaxed text-ink-600">{field.overview}</p><div className="mt-6 flex flex-wrap gap-2">{subjects.map((subject, index) => <Badge key={subject} className={accentSurface[["sky", "lavender", "mint", "butter", "peach"][index % 5] as keyof typeof accentSurface]}>{subject}</Badge>)}</div></div><div className="relative min-h-[250px] lg:min-h-0"><Image src={image} alt="" fill sizes="(max-width: 1024px) 100vw, 48vw" className="object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#f3f7fc] via-transparent to-transparent lg:w-1/3" /></div></section>
        <section id="careers" aria-labelledby="careers-title"><div className="flex items-end justify-between gap-4"><div><h2 id="careers-title" className="text-2xl font-semibold text-[#071533]">Possible careers</h2><p className="mt-1 text-sm text-ink-500">Notice the kinds of work this field can lead towards.</p></div><Link href={`/careers?field=${field.slug}`} className="cb-source hidden text-sm sm:inline-flex">View all careers <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-4 grid gap-4 border-b border-ink-200 pb-6 sm:grid-cols-2 lg:grid-cols-4">{shortCareers.map((career, index) => { const Icon = detailVisuals[index % detailVisuals.length]; return <Link key={career.slug} href={`/careers/${career.slug}`} className="group flex gap-3 rounded-xl p-2 hover:bg-ink-50"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-full ${accentSurface[["sky", "lavender", "mint", "peach"][index % 4] as keyof typeof accentSurface]}`}><Icon className="h-5 w-5 text-[#214b83]" /></span><span><span className="block text-sm font-semibold text-[#071533] group-hover:text-[#2877df]">{career.title}</span><span className="mt-1 block text-xs leading-relaxed text-ink-500">{career.summary}</span></span></Link>; })}</div><Link href={`/careers?field=${field.slug}`} className="cb-source mt-4 ml-auto text-sm sm:hidden">View all careers <ArrowRight className="h-4 w-4" /></Link></section>
        <section id="details" className="grid gap-4 border-t border-ink-100 pt-6 md:grid-cols-3"><div className="rounded-2xl bg-[#f5f9fd] p-5"><h3 className="font-semibold text-[#071533]">Courses & pathways</h3><p className="mt-2 text-sm leading-relaxed text-ink-500">Compare routes, subjects, duration and the next step.</p><ButtonLink href={`/pathways?field=${field.slug}`} variant="secondary" size="sm" className="mt-4">Explore routes<ArrowRight className="h-4 w-4" /></ButtonLink></div><div className="rounded-2xl bg-[#f1faf5] p-5"><h3 className="font-semibold text-[#071533]">Institutions</h3><p className="mt-2 text-sm leading-relaxed text-ink-500">See where related courses and pathways may be available.</p><ButtonLink href={`/institutions?field=${field.slug}`} variant="secondary" size="sm" className="mt-4">Find institutions<ArrowRight className="h-4 w-4" /></ButtonLink></div><div className="rounded-2xl bg-[#fff8e9] p-5"><h3 className="font-semibold text-[#071533]">What to think about</h3><p className="mt-2 text-sm leading-relaxed text-ink-500">Interest matters, but so do time, cost, location and requirements.</p><Link href="/mentor" className="cb-source mt-4 text-sm">Talk it through <ArrowRight className="h-4 w-4" /></Link></div></section>
        <Callout tone="neutral"><p><strong>About this information:</strong> This is general guidance. Check official course, institution and admission sources before acting.</p></Callout>
      </main>
    </div></div>
  </DetailJourneyShell>;
}
