import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Circle, Leaf } from "lucide-react";
import { redirect } from "next/navigation";
import { getExplorationState } from "@/services/profile";
import { getField } from "@/services/catalog";
import { JourneyShell, JourneyIntro, PrimaryLink, SoftCard, StoryBanner } from "@/components/journey";
export const dynamic = "force-dynamic";
const steps = [{ title: "Understand the selected direction", detail: "Build a clear picture before you choose.", href: "/my-journey/direction" }, { title: "Compare two routes", detail: "Notice what each route keeps open.", href: "/my-journey/routes" }, { title: "Shortlist one or two courses", detail: "Look at a smaller set with context.", href: "/my-journey/courses" }, { title: "Check one or two institutions", detail: "Find places where you could study.", href: "/my-journey/institutions" }, { title: "Review deadlines and practical requirements", detail: "Check before you act.", href: "/my-journey/practical" }];
export default async function PlanPage() { const selected = await getExplorationState(); if (!selected) redirect("/my-journey/direction"); const field = await getField(selected.directionSlug); return <JourneyShell current="plan" direction={field?.name}><JourneyIntro eyebrow="Your next steps · Step 8 of 8" title="One small step at a time." description="Keep the things you want to explore in one place. You do not need to solve everything today." /><StoryBanner image="/images/hero-student.png" kicker="A clearer future is built step by step." text="You can keep comparing, asking questions, and changing direction when your understanding changes." /><SoftCard tone="mint" className="mt-7"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-white text-[#2a9c7c]"><Leaf className="h-7 w-7" /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#28775f]">Your next action</p><h2 className="mt-1 text-2xl font-semibold text-[#123f38]">Continue comparing routes</h2><p className="mt-1 text-sm text-[#60766e]">1 of 5 steps complete · No rush</p></div></div><PrimaryLink href="/my-journey/routes">Continue your checklist</PrimaryLink></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#cfe8dc]"><div className="h-full w-1/5 rounded-full bg-[#2a9c7c]" /></div></SoftCard><div className="mt-7 max-w-4xl space-y-3">{steps.map((step, index) => <Link href={step.href} key={step.title} className="group flex items-start gap-4 rounded-2xl border border-[#dce7e5] bg-white p-4 transition hover:-translate-y-0.5 hover:border-[#9bcdb9] hover:shadow-[0_14px_30px_-26px_rgba(18,63,56,.6)]"><span className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-full ${index === 0 ? "bg-[#2a9c7c] text-white" : "border-2 border-[#cbdad6] text-[#879a94]"}`}>{index === 0 ? <Check className="h-4 w-4" /> : <Circle className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-[#123f38]">{step.title}</span><span className="mt-1 block text-sm text-[#71827e]">{step.detail}</span></span><ArrowRight className="mt-1 h-5 w-5 shrink-0 text-[#9bb0aa] transition-transform group-hover:translate-x-1" /></Link>)}</div><p className="mt-7 max-w-2xl text-sm leading-relaxed text-[#82928e]">Your progress is saved on this device. Sign in later if you want to keep it across devices or set reminders.</p></JourneyShell>; }
