import Image from "next/image";
import Link from "next/link";
import { ArrowRight, RefreshCcw } from "lucide-react";
import { redirect } from "next/navigation";
import { getField } from "@/services/catalog";
import { getExplorationState } from "@/services/profile";
import { JourneyShell, JourneyIntro, PrimaryLink, SoftCard } from "@/components/journey";
export const dynamic = "force-dynamic";
export default async function DirectionConfirmPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const [field, selected] = await Promise.all([getField(slug), getExplorationState()]); if (!field || !selected || selected.directionSlug !== slug) redirect("/my-journey/direction"); const image = slug === "technology" ? "/images/field-technology.png" : slug === "healthcare" ? "/images/field-healthcare.png" : slug === "engineering" ? "/images/field-engineering.png" : "/images/possibilities-landscape.png"; return <JourneyShell current="direction" direction={field.name}><JourneyIntro eyebrow="Your choice · Step 2 of 8" title={`You chose ${field.name}.`} description="We will now help you understand this direction step by step. You are not choosing a final career." /><SoftCard tone="mint" className="relative mt-8 max-w-4xl overflow-hidden p-0"><div className="grid md:grid-cols-[.85fr_1.15fr]"><div className="relative min-h-[260px]"><Image src={image} alt="" fill className="object-cover" sizes="420px" /></div><div className="flex flex-col justify-center p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#28775f]">A direction to understand</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[#092b25]">Take a closer look, without rushing.</h2><p className="mt-4 text-base leading-relaxed text-[#60766e]">We will show what this direction includes, the kinds of work it can lead toward, and the routes students often compare.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><PrimaryLink href={`/my-journey/direction/${field.slug}`}>Understand this direction</PrimaryLink><Link href="/my-journey/direction" className="inline-flex min-h-[52px] items-center justify-center gap-2 rounded-xl border border-[#cddbd8] bg-white px-5 text-sm font-semibold text-[#526b68]"><RefreshCcw className="h-4 w-4" />Choose a different direction</Link></div></div></div></SoftCard></JourneyShell>; }
