import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, CalendarDays, CheckCircle2, Coins, FileCheck2, FileText, Landmark, MapPin, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge, ButtonLink, Callout, Eyebrow, VerificationBadge } from "@/components/ui";
import { SaveButton } from "@/components/save-button";
import { getScholarships } from "@/services/catalog";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = (await getScholarships()).find((s) => s.slug === slug); return { title: item?.name ?? "Scholarship" }; }
const tabs = ["Overview", "Eligibility", "Benefits", "Documents", "Sources"];

export default async function ScholarshipPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const scholarship = (await getScholarships()).find((s) => s.slug === slug);
  if (!scholarship) notFound();
  const stages = scholarship.appliesToStage ?? [];
  const stageLabel = stages.map((s) => s === "class10" ? "Class 10" : s === "class12" ? "Class 12" : "Undergraduate").join(" · ") || "Eligible students";
  const documents = scholarship.documents ?? [];
  const official = scholarship.officialUrl ?? scholarship.sourceUrl ?? "#";
  return <div className="bg-white"><div className="cb-container cb-page mx-auto max-w-[1320px]">
    <div className="mb-6 flex items-center gap-3 text-sm text-ink-500"><Link href="/" className="hover:text-forest-700">Home</Link><span>/</span><Link href="/scholarships" className="hover:text-forest-700">Learn</Link><span>/</span><Link href="/scholarships" className="hover:text-forest-700">Scholarships</Link><span>/</span><span className="text-ink-800">{scholarship.name}</span></div>
    <main className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="min-w-0"><header className="relative overflow-hidden rounded-2xl bg-[#f2f8fc] p-6 sm:p-8"><div className="relative z-10 max-w-[720px]"><Eyebrow>Scholarship</Eyebrow><h1 className="mt-3 text-[clamp(2.2rem,4.5vw,4.3rem)] font-semibold leading-[1.04] tracking-[-.05em] text-[#071533]">{scholarship.name}</h1><p className="mt-3 text-xl text-ink-500">Support for students pursuing further study.</p><div className="mt-5 flex flex-wrap gap-3"><Badge>{stageLabel}</Badge><Badge tone="forest">{scholarship.category ?? "Merit-based"}</Badge><Badge><MapPin className="mr-1 inline h-3.5 w-3.5" />Nagaland</Badge></div><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="#eligibility">Check eligibility <ArrowRight className="h-4 w-4" /></ButtonLink><SaveButton itemType="scholarship" itemRef={scholarship.slug} label={scholarship.name} /><a href={official} target="_blank" rel="noreferrer" className="cb-button cb-button-secondary px-5">Visit official source <ArrowRight className="h-4 w-4" /></a></div></div><div className="absolute inset-y-0 right-0 hidden w-[45%] lg:block"><Image src="/images/possibilities-landscape.png" alt="" fill sizes="500px" className="object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-r from-[#f2f8fc] via-[#f2f8fccc] to-transparent" /><Award className="absolute bottom-8 right-24 h-24 w-24 text-[#2877df]/50" /></div></header>
    <nav aria-label="Scholarship sections" className="mt-5 border-b border-ink-200"><ol className="flex gap-1 overflow-x-auto">{tabs.map((tab, index) => <li key={tab}><a href={index === 0 ? "#overview" : index === 1 ? "#eligibility" : "#details"} className={`block whitespace-nowrap border-b-[3px] px-5 py-3 text-sm font-semibold ${index === 0 ? "border-[#198b6e] text-forest-700" : "border-transparent text-ink-500 hover:border-forest-300 hover:text-ink-800"}`}>{tab}</a></li>)}</ol></nav>
    <section id="overview" className="mt-5 rounded-2xl border border-ink-200 bg-white p-6"><h2 className="text-2xl font-semibold text-[#071533]">Who is this for?</h2><p className="mt-3 max-w-3xl text-base leading-relaxed text-ink-600">{scholarship.eligibility ?? `${scholarship.name} is intended to support eligible students continuing their education. Check the official notice for the current criteria.`}</p><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-[#eaf8f2] p-5"><Coins className="h-6 w-6 text-forest-700" /><p className="mt-3 text-sm text-ink-500">Award</p><p className="mt-1 font-semibold text-[#071533]">{scholarship.amountNote ?? "Currently unavailable"}</p><p className="mt-1 text-xs text-ink-500">Check the official notice</p></div><div className="rounded-xl bg-[#f1edff] p-5"><Landmark className="h-6 w-6 text-[#7054b2]" /><p className="mt-3 text-sm text-ink-500">Provider</p><p className="mt-1 font-semibold text-[#071533]">{scholarship.provider ?? "Currently unavailable"}</p><p className="mt-1 text-xs text-ink-500">Scholarship provider</p></div><div className="rounded-xl bg-[#eaf3ff] p-5"><CalendarDays className="h-6 w-6 text-[#2877df]" /><p className="mt-3 text-sm text-ink-500">Deadline</p><p className="mt-1 font-semibold text-[#071533]">{scholarship.deadlineNote ?? "Check official portal"}</p><p className="mt-1 text-xs text-ink-500">Dates may change each year</p></div></div><div className="mt-5 rounded-xl bg-[#fff5df] px-4 py-3 text-sm text-[#86621b]"><FileCheck2 className="mr-2 inline h-4 w-4" />Always confirm the latest details, including eligibility, amount and deadline, on the official notice before applying.</div></section>
    <section id="eligibility" className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-ink-200 p-6"><div className="flex items-center gap-3"><CheckCircle2 className="h-6 w-6 text-forest-700" /><h2 className="text-xl font-semibold">Eligibility</h2></div><p className="mt-4 text-sm leading-relaxed text-ink-600">{scholarship.eligibility ?? "Current eligibility information is unavailable. Check the official source."}</p><div className="mt-5 flex flex-wrap gap-2">{stages.map((stage) => <Badge key={stage}>{stage === "class10" ? "Class 10" : stage === "class12" ? "Class 12" : "Undergraduate"}</Badge>)}</div></article><article id="details" className="rounded-2xl border border-ink-200 p-6"><div className="flex items-center gap-3"><FileText className="h-6 w-6 text-[#7054b2]" /><h2 className="text-xl font-semibold">Documents to keep ready</h2></div><ul className="mt-4 space-y-3">{(documents.length ? documents : ["Mark sheets and certificates", "Identity and address proof", "Bank or account details if required"]).map((doc) => <li key={doc} className="flex gap-2 text-sm text-ink-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-forest-600" />{doc}</li>)}</ul></article></section><Callout tone="neutral"><p>Scholarship information may change from year to year. Verify the current application notice and eligibility with the official provider.</p></Callout></div>
    <aside className="space-y-5"><section className="rounded-2xl bg-[#fffaf0] p-6"><h2 className="text-2xl font-semibold text-[#071533]">Before you apply</h2><p className="mt-2 text-sm leading-relaxed text-ink-500">Make sure you complete these steps to have a smooth application process.</p><ol className="mt-6 space-y-5">{["Check class and marks requirement", "Gather documents", "Confirm deadline"].map((step, index) => <li key={step} className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e1f4ed] font-semibold text-forest-800">{index + 1}</span><div><h3 className="text-sm font-semibold">{step}</h3><p className="mt-1 text-xs leading-relaxed text-ink-500">{index === 0 ? "Ensure you meet the current marks criteria." : index === 1 ? "Keep your mark sheets, ID proof and other required documents ready." : "Note the application deadline and apply before the due date."}</p></div></li>)}</ol></section><section className="rounded-2xl bg-[#eefaf5] p-6"><h2 className="text-2xl font-semibold text-[#071533]">Official source</h2><p className="mt-2 text-sm leading-relaxed text-ink-500">View the official notice and apply through the provider website.</p><div className="mt-5 rounded-xl bg-white px-4 py-3"><VerificationBadge status={scholarship.verificationStatus} lastVerifiedAt={scholarship.lastVerifiedAt} /></div><a href={official} target="_blank" rel="noreferrer" className="cb-button cb-button-primary mt-5 w-full">Visit official source <ArrowRight className="h-4 w-4" /></a></section></aside></main>
  </div></div>;
}
