"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ExternalLink, FileSpreadsheet, Filter, Search, X, XCircle } from "lucide-react";

type ReviewRow = { id: number; name: string; provider: string; eligibility: string; sourceUrl: string | null; verificationStatus: string; lastVerifiedAt: Date | null };
type Status = "accepted" | "needs_review" | "rejected";

function reviewStatus(status: string): Status {
  if (["verified", "current", "recently_verified"].includes(status)) return "accepted";
  if (status.includes("unavailable")) return "rejected";
  return "needs_review";
}

function statusLabel(status: Status) {
  return status === "accepted" ? "Accepted" : status === "rejected" ? "Rejected" : "Needs review";
}

function ReviewRowItem({ row, index, current, checked, onToggle, onStatus }: { row: ReviewRow; index: number; current: Status; checked: boolean; onToggle: () => void; onStatus: (status: Status) => void }) {
  const verificationText = current === "accepted" ? "Verified" : current === "rejected" ? "Rejected" : "Needs review";
  const verificationClass = current === "accepted" ? "text-[#267b62]" : current === "rejected" ? "text-[#bd4b4b]" : "text-[#956b1c]";
  const pillClass = current === "accepted" ? "bg-[#e9f7f0] text-[#267b62]" : current === "rejected" ? "bg-[#fff0f0] text-[#bd4b4b]" : "bg-[#fff7df] text-[#956b1c]";
  return <tr className="border-t border-ink-100 align-middle hover:bg-[#fbfdfc]"><td className="px-4 py-4"><input type="checkbox" checked={checked} onChange={onToggle} aria-label={`Select ${row.name}`} /></td><td className="max-w-[220px] px-4 py-4 font-medium text-[#243b5b]">{index + 1}. {row.name}</td><td className="max-w-[220px] px-4 py-4 text-ink-600">{row.provider}</td><td className="max-w-[180px] px-4 py-4 text-ink-600">{row.eligibility}</td><td className="max-w-[220px] px-4 py-4">{row.sourceUrl ? <a href={row.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-medium text-[#2870aa] hover:underline"><span className="max-w-[180px] truncate">{row.sourceUrl}</span><ExternalLink className="h-3.5 w-3.5 shrink-0" /></a> : <span className="text-xs text-ink-400">Not available</span>}</td><td className="px-4 py-4"><span className={`inline-flex items-center gap-2 text-xs font-medium ${verificationClass}`}>{current === "accepted" ? <CheckCircle2 className="h-4 w-4" /> : current === "rejected" ? <XCircle className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}<span>{verificationText}<small className="block font-normal text-ink-400">{row.lastVerifiedAt ? new Date(row.lastVerifiedAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Not verified"}</small></span></span></td><td className="px-4 py-4"><label className={`inline-flex items-center gap-1 rounded-full px-3 py-2 text-xs font-semibold ${pillClass}`}><span>{statusLabel(current)}</span><select aria-label={`Change status for ${row.name}`} value={current} onChange={(event) => onStatus(event.target.value as Status)} className="cursor-pointer appearance-none bg-transparent outline-none"><option value="needs_review">Needs review</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select><ChevronDown className="h-3.5 w-3.5" /></label></td></tr>;
}

export function ImportReviewTable({ rows }: { rows: ReviewRow[] }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [selected, setSelected] = useState<number[]>([]);
  const [statuses, setStatuses] = useState<Record<number, Status>>(() => Object.fromEntries(rows.map((row) => [row.id, reviewStatus(row.verificationStatus)])));
  const filtered = useMemo(() => rows.filter((row) => `${row.name} ${row.provider} ${row.eligibility}`.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || statuses[row.id] === filter)), [filter, query, rows, statuses]);
  const allVisibleSelected = filtered.length > 0 && filtered.every((row) => selected.includes(row.id));
  const acceptedSelected = selected.filter((id) => statuses[id] === "accepted").length;
  const toggleAll = () => setSelected(allVisibleSelected ? selected.filter((id) => !filtered.some((row) => row.id === id)) : Array.from(new Set([...selected, ...filtered.map((row) => row.id)])));
  const toggleRow = (id: number) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const setRowStatus = (id: number, status: Status) => setStatuses((current) => ({ ...current, [id]: status }));

  return <>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#f2dfaa] bg-[#fff8e6] px-4 py-3 text-sm text-[#8a611b]"><span className="flex items-center gap-2"><AlertTriangle className="h-5 w-5" /><strong>Approval updates the PostgreSQL catalogue.</strong> Please review warnings carefully before approving.</span><button type="button" className="rounded-lg border border-[#eadfbf] bg-white px-3 py-2 text-xs font-semibold text-[#5c4b29]">View import summary</button></div>
    <div className="mt-5 flex flex-wrap gap-3"><label className="relative min-w-[260px] flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search scholarships, providers, eligibility..." className="h-11 w-full rounded-lg border border-ink-200 bg-white pl-10 pr-4 text-sm outline-none focus:border-[#73ae9b] focus:ring-2 focus:ring-[#d9efe6]" /></label>{[{ value: "all", label: "All" }, { value: "needs_review", label: "Needs review" }, { value: "accepted", label: "Accepted" }, { value: "rejected", label: "Rejected" }].map((item) => <button key={item.value} type="button" onClick={() => setFilter(item.value)} className={`inline-flex h-11 items-center gap-2 rounded-lg border px-4 text-sm font-medium ${filter === item.value ? "border-[#8bc7b2] bg-[#effaf5] text-[#267b62]" : "border-ink-200 bg-white text-ink-600 hover:border-[#a8c9bd]"}`}>{item.value !== "all" ? <span className={`h-2 w-2 rounded-full ${item.value === "accepted" ? "bg-[#7fc4a7]" : item.value === "rejected" ? "bg-[#ee9696]" : "bg-[#f4bf3d]"}`} /> : null}{item.label}</button>)}<button type="button" className="inline-flex h-11 items-center gap-2 rounded-lg border border-ink-200 bg-white px-4 text-sm font-medium text-ink-600"><Filter className="h-4 w-4" />Filters <ChevronDown className="h-4 w-4" /></button></div>
    <div className="mt-4 overflow-x-auto rounded-xl border border-ink-200 bg-white"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#f8fafc] text-xs text-ink-500"><tr><th className="w-12 px-4 py-3"><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll} aria-label="Select visible rows" /></th><th className="px-4 py-3 font-semibold">Scholarship name</th><th className="px-4 py-3 font-semibold">Provider</th><th className="px-4 py-3 font-semibold">Eligibility</th><th className="px-4 py-3 font-semibold">Source URL</th><th className="px-4 py-3 font-semibold">Verification</th><th className="px-4 py-3 font-semibold">Status</th></tr></thead><tbody>{filtered.map((row, index) => <ReviewRowItem key={row.id} row={row} index={index} current={statuses[row.id]} checked={selected.includes(row.id)} onToggle={() => toggleRow(row.id)} onStatus={(status) => setRowStatus(row.id, status)} />)}{!filtered.length ? <tr><td colSpan={7} className="px-4 py-12 text-center text-sm text-ink-500">No rows match this search or filter.</td></tr> : null}</tbody></table></div>
    <div className="flex flex-wrap items-center justify-between gap-4 py-4 text-xs text-ink-500"><span>Showing 1 to {filtered.length} of {rows.length} rows</span><div className="flex items-center gap-2"><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-ink-200 bg-white" aria-label="Previous page"><ChevronLeft className="h-4 w-4" /></button><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-[#8bc7b2] bg-[#effaf5] font-semibold text-[#267b62]">1</button><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-ink-200 bg-white">2</button><button type="button" className="grid h-9 w-9 place-items-center rounded-lg border border-ink-200 bg-white" aria-label="Next page"><ChevronRight className="h-4 w-4" /></button></div><span className="rounded-lg border border-ink-200 bg-white px-3 py-2">{Math.min(rows.length, 10)} / page <ChevronDown className="ml-2 inline h-3.5 w-3.5" /></span></div>
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-[#e8e2fb] bg-[#f7f5ff] p-4 sm:px-6"><div className="flex items-center gap-3"><FileSpreadsheet className="h-7 w-7 text-[#7054b2]" /><div><p className="font-semibold text-[#29314d]">{selected.length} rows selected</p><p className="text-xs text-ink-500">Only accepted rows will be added to the catalogue.</p></div></div><div className="flex flex-wrap gap-3"><button type="button" disabled={!selected.length} className="inline-flex items-center gap-2 rounded-lg bg-[#147b58] px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"><Check className="h-4 w-4" />Approve selected ({acceptedSelected})</button><button type="button" disabled={!selected.length} className="inline-flex items-center gap-2 rounded-lg border border-[#e9a1a1] bg-white px-5 py-3 text-sm font-semibold text-[#b44d4d] disabled:cursor-not-allowed disabled:opacity-50"><X className="h-4 w-4" />Reject selected ({selected.filter((id) => statuses[id] === "rejected").length})</button><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-ink-200 bg-white px-5 py-3 text-sm font-semibold text-[#243b5b]"><FileSpreadsheet className="h-4 w-4" />Review source</button></div></div>
  </>;
}
