import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Lightbulb, Route, Sparkles } from "lucide-react";
import { redirect } from "next/navigation";
import { getField } from "@/services/catalog";
import { getExplorationState } from "@/services/profile";
import { JourneyShell, JourneyIntro, PrimaryLink, QuietLink, SoftCard, StoryBanner } from "@/components/journey";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const field = await getField(slug); return { title: field?.name ?? "Direction" }; }
export default async function DirectionDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const [field, selected] = await Promise.all([getField(slug), getExplorationState()]); if (!field || !selected || selected.directionSlug !== slug) redirect("/my-journey/direction"); const image = slug === "technology" ? "/images/field-technology.png" : slug === "healthcare" ? "/images/field-healthcare.png" : slug === "engineering" ? "/images/field-engineering.png" : "/images/possibilities-landscape.png"; return <JourneyShell current="understand" direction={field.name}><JourneyIntro eyebrow="Understand this direction · Step 3 of 8" title={`What is ${field.name.toLowerCase()}?`} description="Before looking at courses or institutions, get a simple picture of what this direction includes." /><div className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><SoftCard tone="white" className="overflow-hidden p-0"><div className="relative h-56"><Image src={image} alt={`${field.name} illustration`} fill className="object-cover object-center" sizes="780px" /></div><div className="p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#effaf5] text-[#287d65]"><Sparkles className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#28775f]">The big picture</p><p className="mt-2 text-base leading-relaxed text-[#60766e]">{field.overview}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><InfoBlock title="What people may do" icon={<BookOpen className="h-4 w-4" />} items={(field.whatPeopleDo ?? []).slice(0, 4)} tone="mint" /><InfoBlock title="Subjects that may help" icon={<Lightbulb className="h-4 w-4" />} items={(field.usefulSubjects ?? []).slice(0, 4)} tone="lavender" /></div><div className="mt-7 flex flex-wrap items-center gap-4"><PrimaryLink href="/my-journey/routes">Compare possible routes</PrimaryLink><QuietLink href={`/explore/${field.slug}`}>Read the full direction guide</QuietLink></div></div></SoftCard><aside className="space-y-5"><SoftCard tone="blue"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2877df]">Keep in mind</p><h2 className="mt-3 text-xl font-semibold text-[#194b71]">A direction can hold many futures.</h2><p className="mt-3 text-sm leading-relaxed text-[#60766e]">You are exploring a direction, not making a final career choice. Compare more than one route before deciding what to look at next.</p></SoftCard><StoryBanner image="/images/pathways-scene.png" kicker="Different routes." text="The next step is to compare how people move toward this direction." tone="lavender" /></aside></div></JourneyShell>; }
function InfoBlock({ title, icon, items, tone }: { title: string; icon: React.ReactNode; items: string[]; tone: "mint" | "lavender" }) { return <div className={`rounded-2xl p-4 ${tone === "mint" ? "bg-[#effaf5]" : "bg-[#f8f5ff]"}`}><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#28775f]">{icon}{title}</p><ul className="mt-3 space-y-2 text-sm leading-relaxed text-[#60766e]">{items.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-1 h-3.5 w-3.5 shrink-0 text-[#2a9c7c]" />{item}</li>)}</ul></div>; }
