import Link from "next/link";
import { ArrowRight, CheckCircle2, RefreshCcw } from "lucide-react";
import { redirect } from "next/navigation";
import { getField } from "@/services/catalog";
import { getExplorationState } from "@/services/profile";
import { JourneyShell, JourneyIntro, PrimaryLink } from "@/components/journey";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const field = await getField(slug); return { title: field?.name ?? "Direction" }; }
export default async function DirectionDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const [field, selected] = await Promise.all([getField(slug), getExplorationState()]); if (!field || !selected || selected.directionSlug !== slug) redirect("/my-journey/direction"); return <JourneyShell current="understand" direction={field.name}><JourneyIntro eyebrow="Step 3 of 8 · Direction selected" title={`You chose ${field.name}.`} description="You are not choosing a final career. We will help you understand this direction, compare routes, and look at real study options." /><section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.75rem] border border-[#cfe8dc] bg-[#effaf5] p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white text-[#287d65]"><CheckCircle2 className="h-6 w-6" /></span><div><h2 className="text-2xl font-semibold text-[#092b25]">What this direction includes</h2><p className="mt-3 text-base leading-relaxed text-ink-600">{field.overview}</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><Info title="What people may do" items={(field.whatPeopleDo ?? []).slice(0, 3)} /><Info title="Subjects that may help" items={(field.usefulSubjects ?? []).slice(0, 4)} /></div><div className="mt-7 flex flex-wrap gap-3"><PrimaryLink href="/my-journey/routes">Compare possible routes</PrimaryLink><Link href={`/explore/${field.slug}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[#6043bd] underline decoration-[#baa9ef] underline-offset-4">Read the full direction guide<ArrowRight className="h-4 w-4" /></Link></div></div><aside className="space-y-4"><div className="rounded-[1.75rem] bg-[#dff0e7] p-6"><div className="grid h-44 place-items-center rounded-2xl bg-[#b8dcca] text-[#287d65]"><span className="text-7xl">{field.icon === "cpu" ? "⌘" : field.icon === "wrench" ? "＋" : "✦"}</span></div><p className="mt-5 text-lg font-semibold text-[#123f38]">A direction can hold many routes.</p><p className="mt-2 text-sm leading-relaxed text-ink-600">Take your time. Compare before you decide what to study.</p></div><form action="/api/exploration" method="post"><input type="hidden" name="clear" value="true" /><button className="inline-flex items-center gap-2 text-sm font-semibold text-ink-500 underline decoration-ink-300 underline-offset-4"><RefreshCcw className="h-4 w-4" />Choose a different direction</button></form></aside></section></JourneyShell>; }
function Info({ title, items }: { title: string; items: string[] }) { return <div className="rounded-2xl bg-white p-4"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#28775f]">{title}</p><ul className="mt-3 space-y-2 text-sm leading-relaxed text-ink-600">{items.map((item) => <li key={item} className="flex gap-2"><span className="text-[#287d65]">•</span>{item}</li>)}</ul></div>; }
