import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, MapPin } from "lucide-react";
import { redirect } from "next/navigation";
import { getField, getInstitutions } from "@/services/catalog";
import { getExplorationState } from "@/services/profile";
import { JourneyShell, JourneyIntro, PrimaryLink, QuietLink, SoftCard, SourceNote, StoryBanner } from "@/components/journey";
export const dynamic = "force-dynamic";
export default async function InstitutionsPage() { const selected = await getExplorationState(); if (!selected) redirect("/my-journey/direction"); const field = await getField(selected.directionSlug); if (!field) redirect("/my-journey/direction"); const institutions = (await getInstitutions({ fieldSlug: field.slug })).slice(0, 6); return <JourneyShell current="institutions" direction={field.name}><JourneyIntro eyebrow="Places to study · Step 6 of 8" title="Where could you study this?" description="These institutions connect with your direction and course choices. Next, we will help you check the practical details." /><StoryBanner image="/images/students-campus.jpg" kicker="Find a place that fits your next step." text="Look nearby and outside Nagaland where relevant. An institution is more than a name — check what it offers and what support is available." tone="blue" /><div className="mt-7 grid gap-5 xl:grid-cols-2">{institutions.map((institution) => <SoftCard key={institution.code} tone="white"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#eff7ff] text-[#2877df]"><Building2 className="h-6 w-6" /></span><div><h2 className="text-xl font-semibold text-[#092b25]">{institution.name}</h2><p className="mt-1 flex items-center gap-1 text-sm text-[#60766e]"><MapPin className="h-3.5 w-3.5" />{institution.district}{institution.city ? ` · ${institution.city}` : ""}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#f7fbf9] p-3"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#28775f]">Type</p><p className="mt-1 text-sm text-[#60766e]">{institution.type} · {institution.ownership}</p></div><div className="rounded-xl bg-[#eff7ff] p-3"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#2877df]">Hostel</p><p className="mt-1 text-sm text-[#60766e]">{institution.hostelAvailable === "unknown" ? "Check with the institution" : institution.hostelAvailable}</p></div></div><p className="mt-4 text-sm leading-relaxed text-[#60766e]">Relevant courses, travel, hostel, and application information should be confirmed before you act.</p><SourceNote /><div className="mt-5 flex flex-wrap items-center gap-4"><Link href="/my-journey/practical" className="cb-button cb-button-primary rounded-xl px-4 py-2.5 text-sm">Review practical details<ArrowRight className="h-4 w-4" /></Link><QuietLink href="/saved">Save institution</QuietLink></div></SoftCard>)}</div>{!institutions.length && <SoftCard tone="white" className="mt-7"><h2 className="text-xl font-semibold text-[#123f38]">No close institution match yet.</h2><p className="mt-2 text-sm leading-relaxed text-[#60766e]">You can still review what to check before applying, and compare options outside the first set.</p></SoftCard>}<div className="mt-8"><PrimaryLink href="/my-journey/practical">Review practical details</PrimaryLink></div></JourneyShell>; }
