import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, CircleHelp, FileCheck2 } from "lucide-react";
import { redirect } from "next/navigation";
import { getExplorationState } from "@/services/profile";
import { getField } from "@/services/catalog";
import { JourneyShell, JourneyIntro, PrimaryLink, SoftCard, SourceNote, StoryBanner } from "@/components/journey";
export const dynamic = "force-dynamic";
const items = ["Check the entry requirement", "Confirm the latest fee", "Check the application deadline", "Ask whether hostel is available", "Keep your documents ready", "Ask what support is available"];
export default async function PracticalPage() { const selected = await getExplorationState(); if (!selected) redirect("/my-journey/direction"); const field = await getField(selected.directionSlug); return <JourneyShell current="practical" direction={field?.name}><JourneyIntro eyebrow="Before you act · Step 7 of 8" title="Keep the practical questions close." description="Use this checklist to turn a possible direction into a careful next step. Facts that change over time should always be checked with the official source." /><StoryBanner image="/images/nagaland-hills.jpg" kicker="Good plans leave room to check." text="A little practical clarity can make the next step feel much lighter." tone="lavender" /><div className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><SoftCard tone="mint"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white text-[#287d65]"><FileCheck2 className="h-6 w-6" /></span><div><h2 className="text-2xl font-semibold text-[#123f38]">Before you apply</h2><p className="mt-2 text-sm leading-relaxed text-[#60766e]">Mark these off as you learn more. You do not have to finish them all today.</p></div></div><div className="mt-6 space-y-3">{items.map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-white px-4 py-3 text-sm text-[#526b68]"><span className="grid h-6 w-6 place-items-center rounded-full border border-[#9bcdb9] text-[#287d65]"><Check className="h-3.5 w-3.5" /></span>{item}</div>)}</div><SourceNote /><div className="mt-6 flex items-start gap-3 rounded-2xl border border-[#d5e7f3] bg-[#eff7ff] p-4"><CircleHelp className="mt-0.5 h-5 w-5 shrink-0 text-[#2877df]" /><p className="text-sm leading-relaxed text-[#60766e]">We do not show unverified fees, dates, or eligibility rules as facts. Check the latest official notice before making a plan.</p></div></SoftCard><SoftCard tone="white"><h2 className="text-xl font-semibold text-[#123f38]">Want a reminder before a deadline?</h2><p className="mt-3 text-sm leading-relaxed text-[#60766e]">Create a free account to save reminders and open this journey on another device. You can also continue without one.</p><div className="mt-6 flex flex-col gap-3"><Link href="/sign-up?returnTo=/my-journey/plan" className="cb-button cb-button-primary justify-center rounded-xl">Create a free account<ArrowRight className="h-4 w-4" /></Link><PrimaryLink href="/my-journey/plan">Not now · see my plan</PrimaryLink></div><div className="mt-8 overflow-hidden rounded-2xl bg-[#eaf3fa] p-3"><Image src="/images/hero-student.png" alt="Student thinking through practical next steps" width={650} height={360} className="h-40 w-full rounded-xl object-cover object-center" /></div></SoftCard></div></JourneyShell>; }
