import Link from "next/link";
import { ArrowRight, Check, CircleHelp } from "lucide-react";
import { getExplorationState } from "@/services/profile";
import { getField } from "@/services/catalog";
import { redirect } from "next/navigation";
import { JourneyShell, JourneyIntro, PrimaryLink, SourceNote } from "@/components/journey";
export const dynamic = "force-dynamic";
const items = ["Check the entry requirement", "Confirm the latest fee", "Check the application deadline", "Ask whether hostel is available", "Keep your documents ready", "Ask the institution what support is available"];
export default async function PracticalPage() { const selected = await getExplorationState(); if (!selected) redirect("/my-journey/direction"); const field = await getField(selected.directionSlug); return <JourneyShell current="practical" direction={field?.name}><JourneyIntro eyebrow="Step 7 of 8 · Before you act" title="Review the practical details." description="Use this checklist to turn a possible direction into a careful next step. Time-sensitive facts should always be checked with the official source." /><section className="mt-8 max-w-3xl rounded-[1.75rem] border border-[#cfe8dc] bg-[#effaf5] p-6 sm:p-8"><h2 className="text-2xl font-semibold text-[#092b25]">Before you apply</h2><div className="mt-5 space-y-3">{items.map((item) => <div key={item} className="flex items-center gap-3 rounded-xl bg-white px-4 py-3 text-sm text-ink-700"><span className="grid h-6 w-6 place-items-center rounded-full border border-[#9bcdb9] text-[#287d65]"><Check className="h-3.5 w-3.5" /></span>{item}</div>)}</div><SourceNote /><div className="mt-7 flex items-start gap-3 rounded-2xl border border-[#d2e2f4] bg-[#eff7ff] p-4"><CircleHelp className="mt-0.5 h-5 w-5 shrink-0 text-[#2877df]" /><p className="text-sm leading-relaxed text-ink-600">We do not show unverified fees, dates, or eligibility rules as facts. Check the latest official notice before making a plan.</p></div></section><section className="mt-6 max-w-3xl rounded-[1.5rem] border border-[#e0d8f6] bg-[#f8f5ff] p-6"><h2 className="text-xl font-semibold text-[#35276f]">Want a reminder before a deadline?</h2><p className="mt-2 text-sm leading-relaxed text-ink-600">Create a free account to save reminders and open this journey on another device. You can also continue without one.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/sign-up?returnTo=/my-journey/plan" className="cb-button cb-button-primary">Create a free account<ArrowRight className="h-4 w-4" /></Link><PrimaryLink href="/my-journey/plan">Not now · see my plan</PrimaryLink></div></section></JourneyShell>; }
