import Image from "next/image";
import Link from "next/link";
import { Compass, Hammer, Layers, Sparkles, Clock3 } from "lucide-react";
import { ArrowGlyph, Badge, ButtonLink, Eyebrow, accentSurface, cx, type Accent } from "@/components/ui";
import { Reveal } from "@/components/reveal";
import { getFields, getPathways } from "@/services/catalog";
import { getSessionState } from "@/services/profile";
import { suggestPathways } from "@/recommendation/engine";

export const dynamic = "force-dynamic";
export const metadata = { title: "Pathways" };

const routeMeta: Record<string, { label: string; accent: Accent; icon: typeof Layers; button: string }> = {
  academic: { label: "Degree route", accent: "mint", icon: Layers, button: "bg-[#2fa77d]" },
  diploma: { label: "Diploma route", accent: "butter", icon: Compass, button: "bg-[#f2bb2e] text-ink-900" },
  vocational: { label: "Skill-first route", accent: "lavender", icon: Hammer, button: "bg-[#7654d4]" },
  professional: { label: "Professional route", accent: "sky", icon: Sparkles, button: "bg-[#2877df]" },
};

export default async function PathwaysPage({ searchParams }: { searchParams: Promise<{ stage?: string; field?: string }> }) {
  const params = await searchParams;
  const stage = params.stage === "class12" ? "class12" : params.stage === "class10" ? "class10" : undefined;
  const [pathways, fields, state] = await Promise.all([getPathways({ stage, fieldSlug: params.field }), getFields(), getSessionState()]);
  const suggested = state ? await suggestPathways(state.snapshot, 3) : [];
  const suggestedSlugs = new Set(suggested.map((s) => s.pathway.slug));
  const featured = ["academic", "diploma", "vocational"].map((type) => pathways.find((pathway) => pathway.routeType === type)).filter((pathway): pathway is NonNullable<typeof pathway> => Boolean(pathway)).slice(0, 3);

  return <div className="relative overflow-hidden">
    <div className="cb-container relative py-10 lg:py-14">
      <div className="relative overflow-hidden rounded-[2rem] bg-[#f5fbfa] px-6 pb-8 pt-10 sm:px-10 lg:px-16 lg:pb-12 lg:pt-14">
        <div className="absolute inset-y-0 right-0 hidden w-1/2 lg:block"><Image src="/images/possibilities-landscape.png" alt="" fill sizes="700px" className="object-cover opacity-25" /><div className="absolute inset-0 bg-gradient-to-r from-[#f5fbfa] via-[#f5fbfaf2] to-transparent" /></div>
        <div className="relative z-10 mx-auto max-w-3xl text-center"><Eyebrow>Ways to get there</Eyebrow><h1 className="mt-4 text-[clamp(2.1rem,5vw,3.6rem)] font-semibold leading-[1.05] tracking-[-.04em] text-[#071533]">There is more than one way forward.</h1><p className="mx-auto mt-4 max-w-2xl text-base text-ink-500 sm:text-lg">Compare routes by time, study style and what they keep open.</p></div>
        <div className="relative z-10 mt-8 flex flex-wrap justify-center gap-2">{[{ href: "/pathways", label: "All routes", active: !stage }, { href: "/pathways?stage=class10", label: "After Class 10", active: stage === "class10" }, { href: "/pathways?stage=class12", label: "After Class 12", active: stage === "class12" }].map((tab) => <Link key={tab.href} href={tab.href} className={cx("rounded-full border px-4 py-2 text-[13px] transition-all", tab.active ? "border-forest-500 bg-forest-600 text-white" : "border-ink-200 bg-white/90 text-ink-600 hover:border-forest-300")}>{tab.label}</Link>)}{params.field ? <Link href={stage ? `/pathways?stage=${stage}` : "/pathways"} className="rounded-full border border-ink-200 bg-white/90 px-4 py-2 text-[13px] text-ink-500">{fields.find((f) => f.slug === params.field)?.name ?? params.field} ×</Link> : null}</div>
      </div>

      {featured.length ? <section className="mt-8" aria-label="Featured routes"><div className="grid gap-5 md:grid-cols-3">{featured.map((pathway, index) => { const meta = routeMeta[pathway.routeType] ?? routeMeta.academic; const Icon = meta.icon; return <Reveal key={pathway.slug} delay={index * 70}><Link href={`/pathways/${pathway.slug}`} className={`group block h-full rounded-2xl border p-5 transition-all hover:-translate-y-1 hover:shadow-lg ${index === 1 ? "border-[#f0d88b] bg-[#fffaf0]" : index === 2 ? "border-[#ddd1fb] bg-[#faf8ff]" : "border-[#cdeade] bg-[#f4fcf8]"}`}><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-white shadow-sm"><Icon className={`h-7 w-7 ${index === 1 ? "text-[#c58d00]" : index === 2 ? "text-[#7654d4]" : "text-forest-700"}`} /></div><h2 className="mt-4 text-center text-xl font-semibold text-[#071533]">{meta.label}</h2><p className="mt-1 text-center text-sm text-ink-500">{index === 0 ? "Deep learning. Wider options." : index === 1 ? "Practical learning. Job-ready sooner." : "Build skills. Gain experience. Keep growing."}</p><div className="mt-5 flex items-center justify-center gap-3 text-xs text-ink-600"><span className={`rounded-full px-3 py-2 ${accentSurface[meta.accent]}`}>{pathway.entryStage === "class10" ? "After Class 10" : "After Class 12"}</span><span className="flex items-center gap-1"><Clock3 className="h-4 w-4" />{pathway.typicalDuration ?? "Flexible"}</span></div><span className={`mt-5 flex items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-semibold text-white ${meta.button}`}>See route <ArrowGlyph className="h-4 w-4" /></span></Link></Reveal>; })}</div><div className="mx-auto mt-5 flex max-w-2xl flex-wrap items-center justify-center gap-4 rounded-2xl border border-[#cfe4f3] bg-[#eef8ff] px-5 py-4 text-sm font-semibold text-ink-800"><Sparkles className="h-5 w-5 text-[#2877df]" />Not sure which route fits? <ButtonLink href="/mentor" variant="secondary" size="sm">Ask Mentor <ArrowRightIcon /></ButtonLink></div></section> : null}

      {suggested.length ? <Reveal><section className="mt-10 rounded-2xl border border-forest-100 bg-forest-50/50 p-6" aria-label="Routes related to you"><p className="inline-flex items-center gap-2 text-sm font-semibold text-forest-800"><Sparkles className="h-4 w-4" />Related to your answers</p><div className="mt-4 grid gap-3 md:grid-cols-3">{suggested.map(({ pathway, reasons }) => <Link key={pathway.slug} href={`/pathways/${pathway.slug}`} className="cb-lift rounded-2xl border border-ink-100 bg-white p-4"><Badge tone="forest">{routeMeta[pathway.routeType]?.label ?? pathway.routeType}</Badge><p className="mt-2.5 text-[14px] font-semibold leading-snug text-ink-900">{pathway.title}</p><p className="mt-1.5 text-[12px] leading-relaxed text-ink-400">{reasons[0]}</p></Link>)}</div></section></Reveal> : null}

      <section className="mt-12" aria-label="All pathways"><div className="mb-4 flex items-end justify-between gap-4"><div><Eyebrow>All routes</Eyebrow><h2 className="mt-2 text-2xl font-semibold text-[#071533]">Explore every pathway</h2></div><span className="text-sm text-ink-500">{pathways.length} routes</span></div><div className="space-y-4">{pathways.map((pathway, index) => { const meta = routeMeta[pathway.routeType] ?? routeMeta.academic; const steps = pathway.steps ?? []; const Icon = meta.icon; return <Reveal key={pathway.slug} delay={Math.min(index * 40, 240)}><Link href={`/pathways/${pathway.slug}`} className={cx("group block rounded-2xl border bg-white p-5 transition-all hover:-translate-y-1 hover:border-forest-300", suggestedSlugs.has(pathway.slug) ? "border-forest-200" : "border-ink-100")}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3.5"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${accentSurface[meta.accent]}`}><Icon className="h-[18px] w-[18px]" /></span><div><div className="flex flex-wrap items-center gap-1.5"><Badge>{pathway.entryStage === "class10" ? "From Class 10" : "From Class 12"}</Badge><Badge tone="forest">{meta.label}</Badge>{pathway.typicalDuration ? <Badge>{pathway.typicalDuration}</Badge> : null}</div><p className="mt-2.5 text-[16px] font-semibold text-ink-900">{pathway.title}</p></div></div><ArrowGlyph className="mt-2 h-4 w-4 shrink-0 text-ink-300 group-hover:text-forest-600" /></div>{steps.length ? <ol className="mt-5 flex flex-wrap items-center gap-x-1.5 gap-y-2 border-t border-dashed border-ink-100 pt-5">{steps.map((step, stepIndex) => <li key={step.label} className="flex items-center gap-1.5"><span className="rounded-full bg-canvas-deep px-3 py-1.5 text-[12px] text-ink-600 group-hover:bg-forest-50">{step.label}</span>{stepIndex < steps.length - 1 ? <span aria-hidden className="text-ink-300">→</span> : null}</li>)}</ol> : null}</Link></Reveal>; })}</div>{!pathways.length ? <p className="mt-6 text-sm text-ink-400">No route matches that filter yet.</p> : null}</section>
      {!state ? <Reveal><div className="mt-12 flex flex-wrap items-center justify-between gap-5 rounded-[1.5rem] border border-ink-100 bg-white p-6 sm:p-8"><div><p className="text-[15px] font-semibold text-ink-900">Which of these fits you?</p><p className="mt-1 text-sm text-ink-500">Answer eight questions and we&apos;ll highlight the closest routes.</p></div><ButtonLink href="/start">Find out <ArrowGlyph /></ButtonLink></div></Reveal> : null}
    </div>
  </div>;
}
function ArrowRightIcon() { return <ArrowGlyph className="h-4 w-4" />; }
