import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Compass, Info } from "lucide-react";
import { redirect } from "next/navigation";
import { getSessionState } from "@/services/profile";
import { suggestFields, type FieldSuggestion } from "@/recommendation/engine";
import { JourneyShell, JourneyIntro, DetailPill, SoftCard, StoryBanner } from "@/components/journey";
export const dynamic = "force-dynamic";
export const metadata = { title: "Choose a direction" };
const imageFor: Record<string, string> = { technology: "/images/field-technology.png", healthcare: "/images/field-healthcare.png", engineering: "/images/field-engineering.png", business: "/images/field-business.png", government: "/images/exams-landscape.png", education: "/images/course-nursing.png", "arts-design": "/images/courses-discovery.png", "science-research": "/images/field-healthcare.png" };
const cardTones = ["blue", "mint", "lavender"] as const;
export default async function DirectionPage() { const state = await getSessionState(); if (!state || state.status !== "completed") redirect("/reflection"); const suggestions = (await suggestFields(state.snapshot, 6)).slice(0, 3); return <JourneyShell current="direction"><JourneyIntro eyebrow="Your possibilities · Step 2 of 8" title="What would you like to explore first?" description="These are broad directions, not final careers. Choose one direction to understand better — you can change your mind later." /><div className="mt-6 flex flex-wrap gap-2"><DetailPill icon={<Info className="h-4 w-4 text-[#765bdd]" />}>Based on what you shared</DetailPill><DetailPill>Not a test result</DetailPill><DetailPill>Not a ranking</DetailPill></div><StoryBanner image="/images/possibilities-landscape.png" kicker="Same roots. Different paths." text="There is no single right route. Start with the direction that makes you curious." /><div className="mt-7 grid gap-5 xl:grid-cols-3">{suggestions.map((suggestion, index) => <DirectionCard key={suggestion.field.slug} suggestion={suggestion} index={index} />)}</div><section className="mt-7 flex flex-col gap-4 rounded-[1.5rem] border border-dashed border-[#cddbd8] bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-[#123f38]">None of these feel right?</h2><p className="mt-1 text-sm text-[#60766e]">That is okay. Your answers are starting points, not a decision.</p></div><Link href="/explore" className="inline-flex items-center gap-2 text-sm font-semibold text-[#6043bd] underline decoration-[#baa9ef] underline-offset-4">See other directions<Compass className="h-4 w-4" /></Link></section></JourneyShell>; }
function DirectionCard({ suggestion, index }: { suggestion: FieldSuggestion; index: number }) { const field = suggestion.field; const image = imageFor[field.slug] ?? "/images/possibilities-landscape.png"; const reason = suggestion.reasons[0]?.detail ?? "This direction connects with some of the interests you shared."; return <SoftCard tone={cardTones[index]} className="flex flex-col overflow-hidden p-0"><div className="relative h-44"><Image src={image} alt="" fill sizes="420px" className="object-cover object-center" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-[11px] font-bold uppercase tracking-[.1em] text-[#28775f]">Possible direction</span></div><div className="flex flex-1 flex-col p-5"><h2 className="text-2xl font-semibold tracking-[-.04em] text-[#092b25]">{field.name}</h2><p className="mt-2 text-sm leading-relaxed text-[#60766e]">{field.tagline ?? field.overview}</p><div className="mt-5 rounded-xl bg-white/75 p-3.5"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#28775f]">Why it appeared</p><p className="mt-2 text-sm leading-relaxed text-[#28584c]">{reason}</p></div><p className="mt-4 text-xs leading-relaxed text-[#71827e]"><strong>Keep in mind:</strong> Understanding a direction is different from choosing a final career.</p><form action="/api/exploration" method="post" className="mt-6"><input type="hidden" name="directionSlug" value={field.slug} /><input type="hidden" name="returnTo" value={`/my-journey/direction/${field.slug}/confirm`} /><button className="cb-button cb-button-primary w-full justify-center rounded-xl">Choose this direction<ArrowRight className="h-4 w-4" /></button></form></div></SoftCard>; }
