"use client";

import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui";

export function SignInForm({ next }: { next: string }) {
  const [showPassword, setShowPassword] = useState(false);
  return <form action="/api/auth/sign-in" method="post" className="mt-7 space-y-5"><input type="hidden" name="next" value={next} /><div><label htmlFor="email" className="mb-2 block text-sm font-semibold text-ink-800">Email</label><div className="relative"><Mail aria-hidden className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-ink-400" /><input id="email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" className="h-14 w-full rounded-xl border border-ink-200 bg-white pl-12 pr-4 text-base outline-none transition focus:border-forest-600 focus:ring-2 focus:ring-forest-100" /></div></div><div><div className="mb-2 flex items-center justify-between gap-3"><label htmlFor="password" className="block text-sm font-semibold text-ink-800">Password</label><a href="#password-help" className="text-sm font-medium text-[#7054b2] underline underline-offset-2">Forgot password?</a></div><div className="relative"><LockKeyhole aria-hidden className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-ink-400" /><input id="password" name="password" type={showPassword ? "text" : "password"} required autoComplete="current-password" placeholder="Enter your password" className="h-14 w-full rounded-xl border border-ink-200 bg-white pl-12 pr-36 text-base outline-none transition focus:border-forest-600 focus:ring-2 focus:ring-forest-100" /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} className="absolute right-3 top-1/2 inline-flex -translate-y-1/2 items-center gap-2 rounded-md px-2 py-1 text-xs font-medium text-ink-500 hover:bg-ink-50 hover:text-ink-800" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}{showPassword ? "Hide password" : "Show password"}</button></div></div><Button type="submit" className="h-14 w-full text-base" size="lg">Sign in <span aria-hidden className="text-xl">→</span></Button></form>;
}
